---
- name: Provision Python Development Environment
  hosts: all
  become: true

  vars:
    project_root: /opt/python-boilerplate
    repo_url: "https://github.com/Retouch-It-Services/devOps-retouch-python-fastapi-boilerplate.git"

  tasks:

    # ---------------------------
    # System preparation
    # ---------------------------
    - name: Refresh apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install base packages
      package:
        name:
          - git
          - curl
          - wget
          - unzip
          - build-essential
          - software-properties-common
        state: present

    # ---------------------------
    # Python installation
    # ---------------------------
    - name: Ensure Python stack is present
      package:
        name:
          - python3
          - python3-pip
          - python3-venv
        state: present

    # ---------------------------
    # Project setup
    # ---------------------------
    - name: Create project directory
      ansible.builtin.file:
        path: "{{ project_root }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Checkout boilerplate repository
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ project_root }}"
        version: main
        force: yes

    - name: Setup virtual environment
      ansible.builtin.command: python3 -m venv {{ project_root }}/venv
      args:
        creates: "{{ project_root }}/venv/bin/activate"

    - name: Install project dependencies
      ansible.builtin.pip:
        requirements: "{{ project_root }}/requirements.txt"
        virtualenv: "{{ project_root }}/venv"
      ignore_errors: true

    - name: Normalize directory permissions
      ansible.builtin.file:
        path: "{{ project_root }}"
        owner: root
        group: root
        recurse: true
